name: "test-local"
on: 
  issues:
    types: [edited, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      with:
        fromMailAddress: 'no-reply@example.com'
        toMailAddress: '${{ secrets.NOTIFY_EMAIL }}'
        subject: 'This is a test'
        subjectPrefix: 'BC:'
        labelsToMonitor: "breaking-change"
        verbose: true
